language: cpp
compiler:
  - gcc
sudo: false
branches:
  only: 
    - master
addons:
  apt:
    packages:
    - python-pip
    - libibus-1.0-dev
    - gtk+-2.0
    - xvfb
#   xvfb is need open display(electron,gtktes)
before_script:
  - pip install --user cpplint
  - nvm install 4.6.0
  - cd settings && npm install && cd ../
script:
  - g++ --version
# - lint test
  - cd settings && npm test && cd ../
  - cpplint --linelength=100 --filter=-readability/casting,-build/namespaces,-build/header_guard *
# - build test
  - mkdir ../kisaragi && cd ../kisaragi
  - cmake ../ibus-mio
  - make
  - make settingbuild
# - TODO(lv7777): make install test(depend with ibus)
# - TODO(lv7777): ibus-mio recognition(ibus list-engine) test(depend with ibus)
# - TODO(lv7777): ./ibus-mio up test(help me how to kill)
# - TODO(lv7777): ./ibus-setup-mio up test(help me how to kill)
# - xvfb-run ./release