language: cpp
compiler:
  - clang
  - gcc
branches:
  only: 
    - ci
addons:
  apt:
    packages:
    - python-pip
    - libibus-1.0-dev
before_script:
  - pip install --user cpplint
script:
  - g++ --version
  - cpplint --linelength=100 --filter=-readability/casting *
  - gcc levena.c $(pkg-config ibus-1.0 --cflags --libs)