language: cpp
compiler:
  - gcc
branches:
  only: 
    - ci
addons:
  apt:
    packages:
    - python-pip
    - libibus-1.0-dev
    - gtk+-2.0
    - xvfb
#   xvfb is need open display(electron,gtktes)
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
# above 2 setting is need open
before_script:
  - pip install --user cpplint
  - nvm install 4.6.0
  - cd settings && npm install && cd ../
script:
  - g++ --version
  - cpplint --linelength=100 --filter=-readability/casting *
  - gcc levena.c $(pkg-config ibus-1.0 --cflags --libs)
  - make build
  - cd settings && npm test