language: cpp
compiler:
  - gcc
sudo: false
branches:
  only: 
    - ci
addons:
  apt:
    packages:
    - python-pip
    - libibus-1.0-dev
    - gtk+-2.0
    - xvfb
#   xvfb is need open display(electron,gtktes)
before_script:
  - pip install --user cpplint
  - nvm install 4.6.0
  - cd settings && npm install && cd ../
script:
  - g++ --version
  - cpplint --linelength=100 --filter=-readability/casting *
  - gcc levena.c $(pkg-config ibus-1.0 --cflags --libs)
  - make build
  - xvfb-run ./release
  - cd settings && npm test